### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 19-ade**
Tried to make a nice readme.md . Hope you like it . Quest6 is empty .

### CODE REVIEW

**Comment by navnit0707** [comment]
Sorry to say but kindly check if this contribution will count or not ....you may try my other repo

**Comment by 19-ade** [comment]
It wont count. But i dont mind . Learning to open-source is the aim isnt it ? :))

**Comment by navnit0707** [comment]
Yes ofcourse.. you learnt something or should i help you further ?

**Comment by navnit0707** [comment]
good job

**Pull request merged**
